export * from './AppIntro/AppIntro';
export * from './ComingSoon/ComingSoon';
export * from './Playground/Playground';

const a = {
  _children: [],
  _internalFiberInstanceHandleDEV: {
    _debugHookTypes: null,
    _debugNeedsRemount: false,
    _debugOwner: {
      _debugHookTypes: ['Array'],
      _debugNeedsRemount: false,
      _debugOwner: ['FiberNode'],
      _debugSource: ['Object'],
      actualDuration: 0,
      actualStartTime: 1661703748161,
      alternate: ['FiberNode'],
      child: ['FiberNode'],
      childLanes: 0,
      deletions: null,
      dependencies: null,
      elementType: ['Function InternalTextInput'],
      flags: 1048577,
      index: 0,
      key: null,
      lanes: 0,
      memoizedProps: ['Object'],
      memoizedState: ['Object'],
      mode: 2,
      pendingProps: ['Object'],
      ref: null,
      return: ['FiberNode'],
      selfBaseDuration: 0,
      sibling: null,
      stateNode: null,
      subtreeFlags: 260,
      tag: 0,
      treeBaseDuration: 0,
      type: ['Function InternalTextInput'],
      updateQueue: ['Object'],
    },
    _debugSource: {
      columnNumber: 7,
      fileName:
        '/Users/canh/react-native-projects/react-native-toolkit/node_modules/react-native/Libraries/Components/TextInput/TextInput.js',
      lineNumber: 1236,
    },
    actualDuration: 0,
    actualStartTime: 1661703748161,
    alternate: {
      _debugHookTypes: null,
      _debugNeedsRemount: false,
      _debugOwner: ['FiberNode'],
      _debugSource: ['Object'],
      actualDuration: 0,
      actualStartTime: 1661703752932,
      alternate: ['Circular'],
      child: null,
      childLanes: 0,
      deletions: null,
      dependencies: null,
      elementType: 'RCTSinglelineTextInputView',
      flags: 260,
      index: 0,
      key: null,
      lanes: 0,
      memoizedProps: ['Object'],
      memoizedState: null,
      mode: 2,
      pendingProps: ['Object'],
      ref: ['Function forwardRef'],
      return: ['FiberNode'],
      selfBaseDuration: 0,
      sibling: null,
      stateNode: ['Circular'],
      subtreeFlags: 0,
      tag: 5,
      treeBaseDuration: 0,
      type: 'RCTSinglelineTextInputView',
      updateQueue: null,
    },
    child: null,
    childLanes: 0,
    deletions: null,
    dependencies: null,
    elementType: 'RCTSinglelineTextInputView',
    flags: 260,
    index: 0,
    key: null,
    lanes: 0,
    memoizedProps: {
      accessible: true,
      allowFontScaling: true,
      blurOnSubmit: true,
      caretHidden: 'undefined',
      clearButtonMode: 'while-editing',
      dataDetectorTypes: 'undefined',
      focusable: true,
      forwardedRef: ['Function ref'],
      mostRecentEventCount: 0,
      onBlur: ['Function _onBlur'],
      onChange: ['Function _onChange'],
      onChangeSync: null,
      onClick: ['Function onClick'],
      onContentSizeChange: 'undefined',
      onFocus: ['Function _onFocus'],
      onKeyPressSync: 'undefined',
      onResponderGrant: ['Function onResponderGrant'],
      onResponderMove: ['Function onResponderMove'],
      onResponderRelease: ['Function onResponderRelease'],
      onResponderTerminate: ['Function onResponderTerminate'],
      onResponderTerminationRequest: ['Function onResponderTerminationRequest'],
      onScroll: ['Function _onScroll'],
      onSelectionChange: ['Function _onSelectionChange'],
      onSelectionChangeShouldSetResponder: [
        'Function emptyFunctionThatReturnsTrue',
      ],
      onStartShouldSetResponder: ['Function onStartShouldSetResponder'],
      placeholder: 'field - 3',
      rejectResponderTermination: true,
      selection: null,
      style: ['Array'],
      text: '',
      underlineColorAndroid: 'transparent',
    },
    memoizedState: null,
    mode: 2,
    pendingProps: {
      accessible: true,
      allowFontScaling: true,
      blurOnSubmit: true,
      caretHidden: 'undefined',
      clearButtonMode: 'while-editing',
      dataDetectorTypes: 'undefined',
      focusable: true,
      forwardedRef: ['Function ref'],
      mostRecentEventCount: 0,
      onBlur: ['Function _onBlur'],
      onChange: ['Function _onChange'],
      onChangeSync: null,
      onClick: ['Function onClick'],
      onContentSizeChange: 'undefined',
      onFocus: ['Function _onFocus'],
      onKeyPressSync: 'undefined',
      onResponderGrant: ['Function onResponderGrant'],
      onResponderMove: ['Function onResponderMove'],
      onResponderRelease: ['Function onResponderRelease'],
      onResponderTerminate: ['Function onResponderTerminate'],
      onResponderTerminationRequest: ['Function onResponderTerminationRequest'],
      onScroll: ['Function _onScroll'],
      onSelectionChange: ['Function _onSelectionChange'],
      onSelectionChangeShouldSetResponder: [
        'Function emptyFunctionThatReturnsTrue',
      ],
      onStartShouldSetResponder: ['Function onStartShouldSetResponder'],
      placeholder: 'field - 3',
      rejectResponderTermination: true,
      selection: null,
      style: ['Array'],
      text: '',
      underlineColorAndroid: 'transparent',
    },
    ref: ['Function forwardRef'],
    return: {
      _debugHookTypes: null,
      _debugNeedsRemount: false,
      _debugOwner: ['FiberNode'],
      _debugSource: ['Object'],
      actualDuration: 0,
      actualStartTime: 1661703748161,
      alternate: ['FiberNode'],
      child: ['Circular'],
      childLanes: 0,
      deletions: null,
      dependencies: null,
      elementType: ['Object'],
      flags: 0,
      index: 0,
      key: null,
      lanes: 0,
      memoizedProps: ['Object'],
      memoizedState: null,
      mode: 2,
      pendingProps: ['Object'],
      ref: null,
      return: ['FiberNode'],
      selfBaseDuration: 0,
      sibling: null,
      stateNode: null,
      subtreeFlags: 260,
      tag: 10,
      treeBaseDuration: 0,
      type: ['Object'],
      updateQueue: null,
    },
    selfBaseDuration: 0,
    sibling: null,
    stateNode: ['Circular'],
    subtreeFlags: 0,
    tag: 5,
    treeBaseDuration: 0,
    type: 'RCTSinglelineTextInputView',
    updateQueue: null,
  },
  _nativeTag: 67,
  clear: ['Function clear'],
  getNativeRef: ['Function getNativeRef'],
  isFocused: ['Function isFocused'],
  setSelection: ['Function setSelection'],
  viewConfig: {
    Commands: {
      blur: 1,
      focus: 0,
      getConstants: 3,
      setTextAndSelection: 2,
    },
    Constants: {},
    Manager: 'SinglelineTextInputViewManager',
    NativeProps: {},
    baseModuleName: 'RCTBaseTextInputView',
    bubblingEventTypes: {
      topBlur: ['Object'],
      topChange: ['Object'],
      topContentSizeChange: ['Object'],
      topEndEditing: ['Object'],
      topFocus: ['Object'],
      topKeyPress: ['Object'],
      topPress: ['Object'],
      topSubmitEditing: ['Object'],
      topTouchCancel: ['Object'],
      topTouchEnd: ['Object'],
      topTouchMove: ['Object'],
      topTouchStart: ['Object'],
    },
    directEventTypes: {
      onGestureHandlerEvent: ['Object'],
      onGestureHandlerStateChange: ['Object'],
      topAccessibilityAction: ['Object'],
      topAccessibilityEscape: ['Object'],
      topAccessibilityTap: ['Object'],
      topChangeSync: ['Object'],
      topKeyPressSync: ['Object'],
      topLayout: ['Object'],
      topMagicTap: ['Object'],
      topScroll: ['Object'],
      topSelectionChange: ['Object'],
      topTextInput: ['Object'],
    },
    uiViewClassName: 'RCTSinglelineTextInputView',
    validAttributes: {
      accessibilityActions: true,
      accessibilityElementsHidden: true,
      accessibilityHint: true,
      accessibilityIgnoresInvertColors: true,
      accessibilityLabel: true,
      accessibilityRole: true,
      accessibilityState: true,
      accessibilityValue: true,
      accessibilityViewIsModal: true,
      accessible: true,
      alignContent: true,
      alignItems: true,
      alignSelf: true,
      allowFontScaling: true,
      aspectRatio: true,
      autoCapitalize: true,
      autoCorrect: true,
      autoFocus: true,
      backfaceVisibility: true,
      backgroundColor: ['Object'],
      blurOnSubmit: true,
      borderBottomColor: ['Object'],
      borderBottomEndRadius: true,
      borderBottomLeftRadius: true,
      borderBottomRightRadius: true,
      borderBottomStartRadius: true,
      borderBottomWidth: true,
      borderColor: ['Object'],
      borderEndColor: ['Object'],
      borderEndWidth: true,
      borderLeftColor: ['Object'],
      borderLeftWidth: true,
      borderRadius: true,
      borderRightColor: ['Object'],
      borderRightWidth: true,
      borderStartColor: ['Object'],
      borderStartWidth: true,
      borderStyle: true,
      borderTopColor: ['Object'],
      borderTopEndRadius: true,
      borderTopLeftRadius: true,
      borderTopRightRadius: true,
      borderTopStartRadius: true,
      borderTopWidth: true,
      borderWidth: true,
      bottom: true,
      caretHidden: true,
      clearButtonMode: true,
      clearTextOnFocus: true,
      collapsable: true,
      color: ['Object'],
      contextMenuHidden: true,
      direction: true,
      display: true,
      editable: true,
      enablesReturnKeyAutomatically: true,
      end: true,
      flex: true,
      flexBasis: true,
      flexDirection: true,
      flexGrow: true,
      flexShrink: true,
      flexWrap: true,
      fontFamily: true,
      fontSize: true,
      fontStyle: true,
      fontVariant: true,
      fontWeight: true,
      height: true,
      hitSlop: ['Object'],
      inputAccessoryViewID: true,
      isHighlighted: true,
      justifyContent: true,
      keyboardAppearance: true,
      keyboardType: true,
      left: true,
      letterSpacing: true,
      lineHeight: true,
      margin: true,
      marginBottom: true,
      marginEnd: true,
      marginHorizontal: true,
      marginLeft: true,
      marginRight: true,
      marginStart: true,
      marginTop: true,
      marginVertical: true,
      maxFontSizeMultiplier: true,
      maxHeight: true,
      maxLength: true,
      maxWidth: true,
      minHeight: true,
      minWidth: true,
      mostRecentEventCount: true,
      multiline: true,
      nativeID: true,
      needsOffscreenAlphaCompositing: true,
      onAccessibilityAction: true,
      onAccessibilityEscape: true,
      onAccessibilityTap: true,
      onChange: true,
      onChangeSync: true,
      onContentSizeChange: true,
      onKeyPressSync: true,
      onLayout: true,
      onMagicTap: true,
      onScroll: true,
      onSelectionChange: true,
      onTextInput: true,
      opacity: true,
      overflow: true,
      padding: true,
      paddingBottom: true,
      paddingEnd: true,
      paddingHorizontal: true,
      paddingLeft: true,
      paddingRight: true,
      paddingStart: true,
      paddingTop: true,
      paddingVertical: true,
      passwordRules: true,
      placeholder: true,
      placeholderTextColor: ['Object'],
      pointerEvents: true,
      position: true,
      removeClippedSubviews: true,
      returnKeyType: true,
      right: true,
      scrollEnabled: true,
      secureTextEntry: true,
      selectTextOnFocus: true,
      selection: true,
      selectionColor: ['Object'],
      shadowColor: ['Object'],
      shadowOffset: ['Object'],
      shadowOpacity: true,
      shadowRadius: true,
      shouldRasterizeIOS: true,
      showSoftInputOnFocus: true,
      spellCheck: true,
      start: true,
      style: ['Object'],
      testID: true,
      text: true,
      textAlign: true,
      textContentType: true,
      textDecorationColor: ['Object'],
      textDecorationLine: true,
      textDecorationStyle: true,
      textShadowColor: ['Object'],
      textShadowOffset: ['Object'],
      textShadowRadius: true,
      textTransform: true,
      top: true,
      transform: ['Object'],
      width: true,
      writingDirection: true,
      zIndex: true,
    },
  },
};
