export const Constants = {
  STATUS: {
    LOADING: 1,
    SUCCESSFUL: 2,
    ERROR: 3,
    IDLE: 4,
  },
  HTTP_CODE: {
    INVALID_PARAMETERS: 'INVALID_PARAMETERS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    SERVER_ERROR: 'SERVER_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
  },
};
