export const Constants = {
  LOADING: 'LOADING',
  SUCCESSFUL: 'SUCCESSFUL',
  ERROR: 'ERROR',
  NOT_READY: 'NOT_READY',

  INVALID_PARAMETERS: 'INVALID_PARAMETERS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SERVER_ERROR: 'SERVER_ERROR',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  NETWORK_REQUEST_FAILED: 'Network request failed',
  NETWORK_ERROR: 'NETWORK_ERROR',
  ACCOUNT_DEACTIVATE: 'ACCOUNT_DEACTIVATE',
};
