const StringsEnglish = {
  AppIntro_next: 'Next',
  App_name: 'base',
  Menu: 'Menu',
  Language: 'Language',
  Mode: 'Mode',
  Current_version: 'Current version',
  English: 'English',
  Japanese: '日本語',
  Vietnamese: 'Tiếng Việt',
  French: 'French',
  Portuguese: 'português',
  Italiano: 'Italiano',
  Light_mode: 'Light mode',
  Dark_mode: 'Dark mode',
  Base_device: 'Based on my phone',
  Appintro_des_1: 'Appintro_des_1',
  Appintro_des_2: 'Appintro_des_2',
  Appintro_des_3: 'Appintro_des_3',
  Login: 'Login',
  Home: 'Home',
  Settings: 'Setting',
  Phone_is_not_empty: 'Phone is required',
  Phone_max_length: 'Phone is invalid',
  Password_is_not_empty: 'Password is not empty',
  Mobile_phone: 'Mobile number',
  Password: 'Password',
  Forgot_password: 'Forgot password?',
  Dont_have_an_account: "Don't have an account?",
  Sign_up: 'Sign up',
  Remember_account: 'Remember account',
  Create_account: 'Create account',
  Have_an_account: 'Already have an account',
  Gallery: 'Gallery',
  Camera: 'Camera',
  Next: 'Next',
  Full_name: 'Full name',
  Full_name_is_not_empty: 'Full name is not empty',
  Avatar_is_required: 'Avatar is required',
  Verify_mobile_number: 'Verify\nmobile number',
  Enter_verification_code: 'Enter the verification code sent to you via SMS.',
  Code: 'Code',
  Code_is_empty: 'Code is empty',
  Set_password: 'Set password',
  Register_vehicle_s: 'Register vehicle(s)',
  Card_number: 'Card number',
  Date: 'Date',
  Duration: 'Duration',
  Start_time: 'Start time',
  Required: 'Required',
  Account_created: 'Account created',
  Account_created_success: 'You have successfully created an account.',
  Go_to_home: 'Go to Home',
  Per_hour: '/hour',
  Navigate: 'Navigate',
  Comunity: 'Comunity',
  Navigation_mode: 'Navigation mode',
  Permission_denided: 'Permisson denied',
  Permission_denided_description: 'You need open setting and giant permission',
  Ok: 'Ok',
  Cancel: 'Cancel',
  Gps: 'Gps',
  Gps_description: 'You must enable Gps',
  Map: 'Map',
  Profile: 'Profile',
  Empty_data: 'Empty data',
  Save: 'Save',
  Bookmark: 'Bookmark',
  History: 'History',
  English_code: 'English_code',
  Search: 'Search',
  Vietnamese_code: 'Vietnamese_code',
  Photo: 'Photo',
};
const StringsVietnamese = {
  AppIntro_next: 'Next',
  App_name: 'base',
  Menu: 'Menu',
  Language: 'Ngôn ngữ',
  Mode: 'Chế độ',
  User_feedback: 'Phản hồi ứng dụng',
  About_us: 'About us',
  Current_version: 'Phiên bản hiện tại',
  English: 'English',
  Japanese: '日本語',
  Vietnamese: 'Tiếng Việt',
  Light_mode: 'Chế độ ban ngày',
  Dark_mode: 'Chế độ ban đêm',
  Base_device: 'Dựa theo điện thoại của bạn.',
  Now: 'Vừa xong',
  Bookmark: 'Yêu thích',
  Settings: 'Cài đặt',
  Login: 'Đăng nhập',
  Home: 'Trang chủ',
  Vietnamese_code: 'Vietnamese_code',
};

export type LanguageCodeType = 'vietnamese' | 'english';

const getResourceStrings = (code: LanguageCodeType) => {
  switch (code) {
    case 'vietnamese':
      return StringsVietnamese;
    case 'english':
      return StringsEnglish;
  }
};

// export type StringsType = ReturnType<typeof getResourceStrings>;
export type StringsType = typeof StringsEnglish;

export {getResourceStrings, StringsEnglish, StringsVietnamese};
