export const Status = {
  UPLOADING: 'UPLOADING',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_SUCCESSUL: 'UPLOAD_SUCCESSUL',
  LOADING: 'LOADING',
  LOAD_FAILED: 'LOAD_FAILED',
  LOAD_SUCCESSFUL: 'LOAD_SUCCESSFUL',
};
